name = "NLPModelsKnitro"
uuid = "bec4dd0d-7755-52d5-9a02-22f0ffc7efcb"
authors = ["Dominique Orban <dominique.orban@gmail.com>"]
version = "0.5.5"

[deps]
KNITRO = "67920dd8-b58e-52a8-8622-53c4cffbe346"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"

[compat]
KNITRO = "0.9, 0.10, 0.11"
NLPModels = "0.14, 0.15, 0.16, 0.17, 0.18"
NLPModelsModifiers = "0.1, 0.2, 0.3, 0.4, 0.5"
SolverCore = "0.1, 0.2"
julia = "1.3.0"

[extras]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ADNLPModels", "LinearAlgebra", "Test"]
